#!/usr/bin/env sh

# Sometimes xbps-src builds a bunch of other junk I don't want to be liable for distributing

COMMAND="
  mkdir /work/packages
  
  cp /work/hostdir/binpkgs/darkly*.xbps /work/packages
  cp /work/hostdir/binpkgs/linux6.14-zen*.xbps /work/packages
  cp /work/hostdir/binpkgs/rofi-wayland*.xbps /work/packages
  cp /work/hostdir/binpkgs/ttf-jetbrains-mono-nerd*.xbps /work/packages
  cp /work/hostdir/binpkgs/vesktop*.xbps /work/packages
  cp /work/hostdir/binpkgs/zen-browser*.xbps /work/packages

  cd /work/packages
  xbps-rindex -a *
"
echo "Running command: $COMMAND"
sh -c "$COMMAND"
