#!/usr/bin/env sh

COMMAND="
  [ \"$TARGET_ARCH\" != \"x86_64\" ] \
    && echo \"BUILD_ARGS=$BUILD_ARGS -a $TARGET_ARCH\" >> \"$GITHUB_ENV\" \
    || true
"

echo "Running command: $COMMAND"
sh -c "$COMMAND"
